apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-01
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-01
  namespace: nginx
spec:
  selector:
    app: nginx-test
  ports:
  - name: http
    port: 80
    targetPort: 80

